name: 'Build'
on:
  pull_request:
    branches:
      - 'master'
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        node: [14, 16]
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn
      - run: tar -czf /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz --exclude="./.git" ./
      - uses: actions/upload-artifact@v3
        with:
          name: chainlink-plugin-${{ matrix.node }}.js.tar.gz
          path: /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz

  lint:
    name: lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: chainlink-plugin-14.js.tar.gz
          path: /tmp
      - run: tar -xf /tmp/chainlink-plugin-14.js.tar.gz -C ./
      - run: yarn lint
