name: Release
on:
  push:
    branches:
      - master
jobs:
  maybe-release:
    name: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:

      - uses: google-github-actions/release-please-action@v3 
        id: release
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":true},{"type":"revert","hidden":true}]'

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - run: corepack enable
        if: ${{ steps.release.outputs.releases_created }}

      - run: yarn install --immutable
        if: ${{ steps.release.outputs.releases_created }}

      - run: yarn build
        if: ${{ steps.release.outputs.releases_created }}

      - run: yarn build:web
        if: ${{ steps.release.outputs.releases_created }}

      - env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
          
      - run: yarn publish --access public
        if: ${{ steps.release.outputs.releases_created }}