name: Test
on:
    workflow_run:
        workflows: ['Build']
        types:
            - completed
    pull_request:
        branches:
            - master
        types:
            - opened
            - reopened
            - synchronize
jobs:
    unit:
        name: Unit Tests
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 14
                    - 16
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: 'chainlink-plugin-${{ matrix.node }}.js.tar.gz'
                  path: /tmp
            - run: 'tar -xf /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz -C ./'
            - run: corepack enable
            - run: 'yarn test:unit'
