name: Test
on:
    pull_request:
        branches:
            - master
        types:
            - opened
            - reopened
            - synchronize
jobs:
    build:
        name: Build TSC
        strategy:
            matrix:
                node:
                    - 14
                    - 16
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '${{ matrix.node }}'
                  cache: yarn
            - run: corepack enable
            - run: yarn install
            - run: >-
                  tar -czf /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz
                  --exclude="./.git" ./
            - uses: actions/upload-artifact@v3
              with:
                  name: 'chainlink-plugin-${{ matrix.node }}.js.tar.gz'
                  path: '/tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz'
    build-web:
        name: Build Webpack
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 14
                    - 16
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: 'chainlink-plugin-${{ matrix.node }}.js.tar.gz'
                  path: /tmp
            - run: corepack enable
            - run: 'tar -xf /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz -C ./'
            - run: 'yarn build:web'
            - run: >-
                  tar -czf /tmp/chainlink-plugin-webpack-${{ matrix.node }}.js.tar.gz
                  --exclude="./.git" ./
            - uses: actions/upload-artifact@v3
              with:
                  name: 'chainlink-plugin-webpack-${{ matrix.node }}.js.tar.gz'
                  path: '/tmp/chainlink-plugin-webpack-${{ matrix.node }}.js.tar.gz'
    lint:
        name: lint
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: chainlink-plugin-14.js.tar.gz
                  path: /tmp
            - run: corepack enable
            - run: tar -xf /tmp/chainlink-plugin-14.js.tar.gz -C ./
            - run: yarn lint
    unit:
        name: Unit Tests
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 14
                    # - 16
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: 'chainlink-plugin-${{ matrix.node }}.js.tar.gz'
                  path: /tmp
            - run: 'tar -xf /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz -C ./'
            - run: corepack enable
            - run: 'yarn test:unit'
    browser-tests:
        name: Browser Tests
        needs: build-web
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 16
                browser: ['electron', 'chrome', 'firefox']
        steps:
            - uses: browser-actions/setup-firefox@latest
              if: matrix.browser == 'firefox'
            - uses: actions/download-artifact@v3
              with:
                  name: 'chainlink-plugin-webpack-${{ matrix.node }}.js.tar.gz'
                  path: /tmp
            - run: 'tar -xf /tmp/chainlink-plugin-webpack-${{ matrix.node }}.js.tar.gz -C ./'
            - run: corepack enable
            - uses: cypress-io/github-action@v5
              with:
                  install: false
                  browser: matrix.browser
                  command: 'yarn test:e2e:${{ matrix.browser }}'
                  cache-key: node-v${{ matrix.node }}-on-${{ matrix.browser }}-hash-${{ hashFiles('yarn.lock') }}
