name: Test
'on':
    pull_request:
        branches:
            - master
        types:
            - opened
            - reopened
            - synchronize
jobs:
    build:
        name: Build TSC
        strategy:
            matrix:
                node:
                    - 14
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '${{ matrix.node }}'
                  cache: yarn
            - run: corepack enable
            - run: yarn install
            - run: >-
                  tar -czf /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz
                  --exclude="./.git" ./
            - uses: actions/upload-artifact@v3
              with:
                  name: 'chainlink-plugin-${{ matrix.node }}.js.tar.gz'
                  path: '/tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz'
    unit:
        name: Unit Tests
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 14
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: 'chainlink-plugin-${{ matrix.node }}.js.tar.gz'
                  path: /tmp
            - run: 'tar -xf /tmp/chainlink-plugin-${{ matrix.node }}.js.tar.gz -C ./'
            - run: corepack enable
            - run: 'yarn test:unit'
    browser-test-chrome:
        name: Browser Tests - Chrome
        needs: build-web
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 14
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: 'chainlink-plugin-webpack-${{ matrix.node }}.js.tar.gz'
                  path: /tmp
            - run: >-
                  tar -xf /tmp/chainlink-plugin-webpack-${{ matrix.node }}.js.tar.gz -C
                  ./
            - run: corepack enable
            - uses: cypress-io/github-action@v5
              with:
                  install: true
                  browser: chrome
                  command: 'yarn test:e2e:chrome'
                  cache-key: >-
                      node-v${{ matrix.node }}-on-chrome-hash-${{ hashFiles('yarn.lock')
                      }}
